[2021-09-29 14:29:21] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [118]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:29:30] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [118]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:29:39] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [118]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:30:46] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [118]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:30:55] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [118]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:31:05] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [118]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:31:14] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [118]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:31:23] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [118]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:31:32] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [118]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:31:42] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [118]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:31:51] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [118]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:32:00] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [118]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:32:09] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [118]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:32:23] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [118]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:32:33] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [118]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:32:42] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [118]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:32:51] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [118]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:33:00] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [118]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:33:10] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [118]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:33:19] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [118]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:33:28] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [118]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:33:42] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [120]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:35:18] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [119]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:37:14] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [119]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:40:29] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [118]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:40:38] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [118]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:40:47] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [118]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:40:56] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [118]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:41:06] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [118]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:41:15] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [118]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:41:50] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [118]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:42:06] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [118]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:42:23] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [118]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:43:06] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [118]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:43:43] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [118]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:46:58] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [119]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:47:41] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [119]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:50:25] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [119]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:50:41] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [119]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:50:57] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [119]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 14:51:13] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [119]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 15:27:05] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [121]:Other error occur [wxt536]:[192.168.1.149]:[4001]:__reconnect() missing 1 required positional argument: 'statement'
[2021-09-29 15:27:46] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [120]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 15:28:03] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [120]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 15:28:37] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [120]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 15:29:03] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [120]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 15:29:19] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [120]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 15:29:35] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [120]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 15:29:51] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [120]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 15:30:08] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [120]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 15:30:24] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [120]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 15:30:40] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [120]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 15:32:08] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [122]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 15:33:40] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [122]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 15:34:22] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [122]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 15:35:26] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [122]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 15:38:12] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [122]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 15:38:38] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [122]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 15:39:02] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [122]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 15:39:18] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [122]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 15:39:38] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [122]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 15:39:54] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [122]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 15:40:15] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [122]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 15:40:31] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [122]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 15:41:02] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [122]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 15:42:46] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [121]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
[2021-09-29 15:44:55] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-error [121]:Other error occur [wxt536]:[192.168.1.149]:[4001]:timed out
