[2021-08-20 10:33:37] E:\WorkSpace\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-08-20 10:33:37] E:\WorkSpace\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-08-20 10:33:41] E:\WorkSpace\DataCollection\connectors\tcp_connector.py-info [60]:Connect to [wxt536]:[192.168.1.84]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!!
[2021-08-20 10:33:45] E:\WorkSpace\DataCollection\connectors\tcp_connector.py-info [76]:Reconnect to [wxt536]:[192.168.1.84]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-08-20 10:33:54] E:\WorkSpace\DataCollection\connectors\tcp_connector.py-info [76]:Reconnect to [wxt536]:[192.168.1.84]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-08-20 10:34:25] E:\WorkSpace\DataCollection\connectors\tcp_connector.py-info [57]:Connect to [wxt536]:[192.168.1.84]:[4001] success !
[2021-08-20 10:34:25] E:\WorkSpace\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-08-20 10:34:25] E:\WorkSpace\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-08-20 10:35:26] E:\WorkSpace\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-08-20 10:35:26] E:\WorkSpace\DataCollection\connectors\tcp_connector.py-info [57]:Connect to [wxt536]:[192.168.1.84]:[4001] success !
[2021-08-20 10:35:26] E:\WorkSpace\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-08-20 10:36:14] E:\WorkSpace\DataCollection\connectors\tcp_connector.py-info [57]:Connect to [wxt536]:[192.168.1.84]:[4001] success !
[2021-08-20 10:36:14] E:\WorkSpace\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-08-20 10:36:14] E:\WorkSpace\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-08-20 10:37:08] E:\WorkSpace\DataCollection\connectors\tcp_connector.py-info [57]:Connect to [wxt536]:[192.168.1.84]:[4001] success !
[2021-08-20 10:37:08] E:\WorkSpace\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-08-20 10:37:08] E:\WorkSpace\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-08-20 10:40:35] E:\WorkSpace\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-08-20 10:40:35] E:\WorkSpace\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-08-20 10:40:37] E:\WorkSpace\DataCollection\connectors\tcp_connector.py-info [60]:Connect to [wxt536]:[192.168.1.84]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!!
[2021-08-20 10:40:39] E:\WorkSpace\DataCollection\connectors\tcp_connector.py-info [76]:Reconnect to [wxt536]:[192.168.1.84]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-08-20 10:40:46] E:\WorkSpace\DataCollection\connectors\tcp_connector.py-info [76]:Reconnect to [wxt536]:[192.168.1.84]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-08-20 10:40:53] E:\WorkSpace\DataCollection\connectors\tcp_connector.py-info [76]:Reconnect to [wxt536]:[192.168.1.84]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-08-20 10:41:00] E:\WorkSpace\DataCollection\connectors\tcp_connector.py-info [76]:Reconnect to [wxt536]:[192.168.1.84]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-08-20 10:41:05] E:\WorkSpace\DataCollection\connectors\tcp_connector.py-info [73]:Reconnect to [wxt536]:[192.168.1.84]:[4001] success !
[2021-08-20 10:47:17] E:\WorkSpace\DataCollection\connectors\tcp_connector.py-info [57]:Connect to [wxt536]:[192.168.1.84]:[4001] success !
[2021-08-20 10:47:17] E:\WorkSpace\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-08-20 10:47:17] E:\WorkSpace\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-08-20 10:48:20] E:\WorkSpace\DataCollection\connectors\tcp_connector.py-info [57]:Connect to [wxt536]:[192.168.1.84]:[4001] success !
[2021-08-20 10:48:20] E:\WorkSpace\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-08-20 10:48:20] E:\WorkSpace\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-08-23 19:04:32] E:\WorkSpace\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-08-23 19:04:32] E:\WorkSpace\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-08-24 08:34:50] E:\WorkSpace\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-08-24 08:34:50] E:\WorkSpace\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-08-24 08:35:11] E:\WorkSpace\DataCollection\connectors\tcp_connector.py-info [60]:Connect to [wxt536]:[192.168.1.84]:[4001] failed:[WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 !!!
[2021-08-24 08:35:21] E:\WorkSpace\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-08-24 08:35:21] E:\WorkSpace\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-08-24 08:35:42] E:\WorkSpace\DataCollection\connectors\tcp_connector.py-info [60]:Connect to [wxt536]:[192.168.1.84]:[4001] failed:[WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 !!!
[2021-08-24 18:58:30] E:\WorkSpace\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-08-24 18:58:30] E:\WorkSpace\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-24 15:03:12] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-24 15:03:12] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-24 15:05:43] E:\WorkSpace\shuicai\DataCollection\connectors\shuizhi_tcp_connector.py-info [49]:Connect to [shuizhi]:[192.168.127.254]:[4001] success !
[2021-09-24 15:25:19] E:\WorkSpace\shuicai\DataCollection\connectors\shuizhi_tcp_connector.py-info [49]:Connect to [shuizhi]:[192.168.127.254]:[4001] success !
[2021-09-24 15:56:38] E:\WorkSpace\shuicai\DataCollection\connectors\shuizhi_tcp_connector.py-info [49]:Connect to [shuizhi]:[192.168.127.254]:[4001] success !
[2021-09-24 16:00:29] E:\WorkSpace\shuicai\DataCollection\connectors\shuizhi_tcp_connector.py-info [49]:Connect to [shuizhi]:[192.168.127.254]:[4001] success !
[2021-09-24 16:02:30] E:\WorkSpace\shuicai\DataCollection\connectors\shuizhi_tcp_connector.py-info [49]:Connect to [shuizhi]:[192.168.127.254]:[4001] success !
[2021-09-24 16:03:28] E:\WorkSpace\shuicai\DataCollection\connectors\shuizhi_tcp_connector.py-info [49]:Connect to [shuizhi]:[192.168.127.254]:[4001] success !
[2021-09-24 16:07:39] E:\WorkSpace\shuicai\DataCollection\connectors\shuizhi_tcp_connector.py-info [49]:Connect to [shuizhi]:[192.168.127.254]:[4001] success !
[2021-09-24 16:08:05] E:\WorkSpace\shuicai\DataCollection\connectors\shuizhi_tcp_connector.py-info [49]:Connect to [shuizhi]:[192.168.127.254]:[4001] success !
[2021-09-24 17:14:17] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-24 17:14:17] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-24 17:14:38] E:\WorkSpace\shuicai\DataCollection\connectors\shuizhi_tcp_connector.py-info [52]:Connect to [shuizhi]:[192.168.127.254]:[4001] failed:[WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 !!!
[2021-09-24 17:14:59] E:\WorkSpace\shuicai\DataCollection\connectors\shuizhi_tcp_connector.py-info [68]:Reconnect to [shuizhi]:[192.168.127.254]:[4001] failed:[WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 !!! Continue reconnect in 5s..
[2021-09-24 17:15:25] E:\WorkSpace\shuicai\DataCollection\connectors\shuizhi_tcp_connector.py-info [68]:Reconnect to [shuizhi]:[192.168.127.254]:[4001] failed:[WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 !!! Continue reconnect in 5s..
[2021-09-24 17:15:51] E:\WorkSpace\shuicai\DataCollection\connectors\shuizhi_tcp_connector.py-info [68]:Reconnect to [shuizhi]:[192.168.127.254]:[4001] failed:[WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 !!! Continue reconnect in 5s..
[2021-09-24 17:16:17] E:\WorkSpace\shuicai\DataCollection\connectors\shuizhi_tcp_connector.py-info [68]:Reconnect to [shuizhi]:[192.168.127.254]:[4001] failed:[WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 !!! Continue reconnect in 5s..
[2021-09-24 17:16:43] E:\WorkSpace\shuicai\DataCollection\connectors\shuizhi_tcp_connector.py-info [68]:Reconnect to [shuizhi]:[192.168.127.254]:[4001] failed:[WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 !!! Continue reconnect in 5s..
[2021-09-24 17:17:09] E:\WorkSpace\shuicai\DataCollection\connectors\shuizhi_tcp_connector.py-info [68]:Reconnect to [shuizhi]:[192.168.127.254]:[4001] failed:[WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 !!! Continue reconnect in 5s..
[2021-09-24 17:17:35] E:\WorkSpace\shuicai\DataCollection\connectors\shuizhi_tcp_connector.py-info [68]:Reconnect to [shuizhi]:[192.168.127.254]:[4001] failed:[WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 !!! Continue reconnect in 5s..
[2021-09-24 17:18:01] E:\WorkSpace\shuicai\DataCollection\connectors\shuizhi_tcp_connector.py-info [68]:Reconnect to [shuizhi]:[192.168.127.254]:[4001] failed:[WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 !!! Continue reconnect in 5s..
[2021-09-29 14:25:56] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 14:25:56] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 14:25:59] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [61]:Connect to [wxt536]:[192.168.1.84]:[4001] failed:timed out !!!
[2021-09-29 14:26:20] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [79]:Reconnect to [wxt536]:[192.168.1.84]:[4001] failed:[WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 !!! Continue reconnect in 5s..
[2021-09-29 14:26:46] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [79]:Reconnect to [wxt536]:[192.168.1.84]:[4001] failed:[WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 !!! Continue reconnect in 5s..
[2021-09-29 14:27:12] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [79]:Reconnect to [wxt536]:[192.168.1.84]:[4001] failed:[WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 !!! Continue reconnect in 5s..
[2021-09-29 14:27:38] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [79]:Reconnect to [wxt536]:[192.168.1.84]:[4001] failed:[WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 !!! Continue reconnect in 5s..
[2021-09-29 14:28:04] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [79]:Reconnect to [wxt536]:[192.168.1.84]:[4001] failed:[WinError 10053] 你的主机中的软件中止了一个已建立的连接。 !!! Continue reconnect in 5s..
[2021-09-29 14:28:30] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [79]:Reconnect to [wxt536]:[192.168.1.84]:[4001] failed:[WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 !!! Continue reconnect in 5s..
[2021-09-29 14:28:49] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 14:28:49] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [57]:Connect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:28:49] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 14:29:17] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [57]:Connect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:29:17] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 14:29:17] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 14:29:26] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [75]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:29:35] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [75]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:29:44] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [75]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:30:42] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [57]:Connect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:30:42] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 14:30:42] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 14:30:51] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [75]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:31:00] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [75]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:31:10] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [75]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:31:19] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [75]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:31:28] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [75]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:31:37] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [75]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:31:47] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [75]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:31:56] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [75]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:32:05] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [75]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:32:12] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [57]:Connect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:32:12] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 14:32:12] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 14:32:28] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [75]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:32:38] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [75]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:32:47] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [75]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:32:56] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [75]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:33:05] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [75]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:33:15] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [75]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:33:24] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [75]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:33:32] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [57]:Connect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:33:32] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 14:33:32] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 14:33:38] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 14:33:38] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [57]:Connect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:33:38] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 14:33:47] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [77]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:34:55] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 14:34:55] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [57]:Connect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:34:55] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 14:35:23] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [77]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:37:10] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 14:37:10] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [57]:Connect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:37:10] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 14:37:19] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [77]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:40:12] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [57]:Connect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:40:12] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 14:40:12] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 14:40:25] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 14:40:25] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [57]:Connect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:40:25] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 14:40:34] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [76]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:40:43] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [76]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:40:52] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [76]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:41:01] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [76]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:41:11] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [76]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:41:20] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 14:41:20] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [57]:Connect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:41:20] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 14:41:55] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [76]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:42:11] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [76]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:42:28] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [76]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:43:11] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [76]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:43:48] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [76]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:45:43] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [57]:Connect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:45:43] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 14:45:43] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 14:45:48] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [57]:Connect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:45:48] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 14:45:48] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 14:45:51] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [57]:Connect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:45:51] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 14:45:51] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 14:46:31] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 14:46:31] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 14:46:33] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 14:46:33] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 14:46:35] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [61]:Connect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!!
[2021-09-29 14:46:38] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 14:46:38] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 14:46:39] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [61]:Connect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!!
[2021-09-29 14:46:41] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [80]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 14:46:46] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [76]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:47:03] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [76]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:47:46] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [76]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:49:47] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 14:49:47] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 14:49:49] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [61]:Connect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!!
[2021-09-29 14:49:51] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [80]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 14:49:58] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [80]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 14:50:04] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [76]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:50:30] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [76]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:50:46] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [76]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:51:02] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [76]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 14:51:18] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [76]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:23:29] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 15:23:29] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 15:23:59] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 15:23:59] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 15:24:01] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [61]:Connect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!!
[2021-09-29 15:24:01] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [76]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:24:55] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [57]:Connect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:24:55] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 15:24:55] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 15:26:57] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 15:26:57] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 15:26:59] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [61]:Connect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!!
[2021-09-29 15:27:01] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [76]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:27:25] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 15:27:25] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 15:27:25] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [57]:Connect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:27:35] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [75]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:27:51] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [75]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:28:08] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [75]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:28:20] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 15:28:20] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 15:28:20] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [57]:Connect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:28:26] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [75]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:28:42] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [75]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:28:51] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [75]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:29:08] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [75]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:29:24] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [75]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:29:40] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [75]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:29:56] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [75]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:30:13] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [75]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:30:29] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [75]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:30:47] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 15:30:47] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [57]:Connect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:30:47] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 15:30:53] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 15:30:53] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [57]:Connect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:30:53] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 15:30:57] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [77]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:31:32] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 15:31:32] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 15:31:34] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [61]:Connect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!!
[2021-09-29 15:31:36] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:31:43] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:31:50] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:31:57] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [77]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:32:13] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [77]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:33:25] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 15:33:25] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [57]:Connect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:33:25] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 15:33:45] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [77]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:34:07] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [57]:Connect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:34:07] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 15:34:07] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 15:34:27] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [77]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:35:10] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 15:35:10] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [57]:Connect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:35:10] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 15:35:31] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [77]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:37:56] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 15:37:56] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [57]:Connect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:37:56] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 15:38:17] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [77]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:38:43] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [77]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:38:51] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 15:38:51] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [57]:Connect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:38:51] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 15:39:07] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [77]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:39:23] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [77]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:39:43] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [77]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:39:59] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [77]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:40:20] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [77]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:40:36] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [77]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:40:44] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 15:40:44] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 15:40:44] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [57]:Connect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:40:48] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 15:40:48] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [57]:Connect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:40:48] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 15:41:07] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [77]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:42:32] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 15:42:32] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [57]:Connect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:42:32] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 15:42:51] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [77]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:43:02] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:43:09] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:43:14] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 15:43:14] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 15:43:16] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [61]:Connect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!!
[2021-09-29 15:43:16] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [77]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:44:35] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 15:44:35] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 15:44:37] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [61]:Connect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!!
[2021-09-29 15:44:39] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:44:44] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [77]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:45:02] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:45:07] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [77]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:45:24] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [77]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:45:34] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:45:41] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:45:49] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:45:56] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 15:45:56] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 15:45:57] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [57]:Connect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:46:05] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:46:12] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:46:18] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [77]:Reconnect to [wxt536]:[192.168.1.149]:[4001] success !
[2021-09-29 15:46:27] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:46:34] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:46:37] E:\WorkSpace\shuicai\DataCollection\historical_data_storage.py-info [16]:[HistoricalDataStorage] - Historical data storage module is running!
[2021-09-29 15:46:37] E:\WorkSpace\shuicai\DataCollection\alarm.py-info [53]:[overrun_alarm] - Over run alarm module is running!
[2021-09-29 15:46:38] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [61]:Connect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!!
[2021-09-29 15:46:40] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:46:47] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:46:54] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:47:01] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:47:08] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:47:15] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:47:23] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:47:30] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:47:37] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:47:44] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:47:51] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:47:58] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:48:05] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:48:12] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:48:19] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:48:26] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:48:33] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:48:40] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:48:47] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:48:54] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:49:01] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:49:08] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:49:15] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:49:22] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:49:29] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:49:36] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:49:43] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:49:50] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:49:57] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:50:04] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:50:11] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:50:18] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:50:25] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:50:32] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:50:39] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:50:46] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:50:53] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:51:00] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:51:07] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:51:14] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:51:21] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:51:28] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:51:35] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:51:42] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:51:49] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:51:56] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:52:03] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:52:10] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:52:17] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:52:24] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:52:31] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:52:38] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:52:45] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:52:52] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:52:59] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:53:06] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:53:13] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:53:20] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:53:27] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:53:34] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:53:41] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:53:48] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:53:55] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:54:02] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:54:09] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:54:16] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:54:23] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:54:30] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:54:37] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:54:44] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:54:51] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:54:58] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:55:05] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:55:12] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:55:19] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:55:26] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:55:33] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:55:40] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:55:47] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:55:55] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:56:02] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:56:09] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:56:16] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:56:23] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:56:30] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:56:37] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:56:44] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:56:51] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:56:58] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:57:05] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:57:12] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:57:19] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:57:26] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:57:33] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:57:40] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:57:47] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:57:54] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:58:01] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:58:08] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:58:15] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:58:22] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:58:29] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:58:36] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:58:43] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:58:50] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:58:57] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:59:04] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:59:11] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:59:18] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:59:25] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:59:32] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:59:39] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:59:46] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 15:59:53] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:00:00] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:00:07] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:00:14] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:00:21] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:00:28] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:00:35] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:00:42] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:00:49] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:00:56] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:01:03] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:01:10] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:01:17] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:01:24] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:01:31] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:01:38] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:01:45] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:01:52] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:01:59] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:02:06] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:02:13] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:02:20] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:02:27] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:02:34] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:02:41] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:02:48] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:02:55] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:03:02] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:03:09] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:03:16] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:03:23] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:03:30] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:03:37] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:03:44] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:03:51] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:03:58] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:04:05] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:04:12] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:04:20] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:04:27] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:04:34] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:04:41] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:04:48] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:04:55] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:05:02] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:05:09] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:05:16] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:05:23] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:05:30] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:05:37] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:05:44] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:05:51] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:05:58] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:06:05] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:06:12] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:06:19] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:06:26] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:06:33] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:06:40] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:06:47] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:06:54] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:07:01] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:07:08] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:07:15] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:07:22] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:07:29] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:07:36] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:07:43] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:07:50] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:07:57] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:08:04] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:08:11] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:08:18] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:08:25] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:08:32] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:08:39] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:08:46] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:08:53] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
[2021-09-29 16:09:00] E:\WorkSpace\shuicai\DataCollection\connectors\tcp_connector.py-info [81]:Reconnect to [wxt536]:[192.168.1.149]:[4001] failed:[WinError 10061] 由于目标计算机积极拒绝，无法连接。 !!! Continue reconnect in 5s..
